beholder {
  api.key = "foo"
  api.key = ${?BEHOLDER_API_KEY}
  cache {
    size = 500
    size = ${?BEHOLDER_CACHE_SIZE} # size in MB
    freepct = 0.20                   
    freepct = ${?BEHOLDER_CACHE_FREEPCT} # free space in % when cache is full
  }
  ffmpeg {
    path = "ffmpeg"
    path = ${?BEHOLDER_FFMPEG_PATH}
  }
  ffprobe {
    cache {
      maxcount = 5000 # max number of files in cache
      maxcount = ${?BEHOLDER_FFPROBE_CACHE_MAXCOUNT}
      expire = 12h
      expire = ${?BEHOLDER_FFPROBE_CACHE_EXPIRE} # expire time for cache entries
    }
    path = "ffprobe"
    path = ${?BEHOLDER_FFPROBE_PATH}
  }
  http {
    port = 8080
    port = ${?BEHOLDER_HTTP_PORT}
  }
}