// addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.7.0")
addSbtPlugin("com.github.sbt"    % "sbt-git"             % "2.1.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.11.7")
addSbtPlugin("com.github.sbt"    % "sbt-header"          % "5.11.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.6.1")